spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
server:
  port: 8084
  
springdoc:
  swagger-ui:
    path: /swagger-ui.html
